### ISSUE TITLE
[ZS] Unique Charged Attacks for Melee Weapons

### ISSUE THREAD

**Issue by ProfDru** [Raox2/sunrust-suggestions#65]
# Preface
While using most melee weapons, a player can hold down mouse 1 to deliver a more powerful attack at the cost of more windup. This is true for nearly every weapon capable of charging attacks,  with the exception of one:

### Axe (T1)
- Charged attacks cleave through zombies

This charged attack is a small situational bonus, but provides the axe with its own identity as a weapon, distinguishing it from the other weapons in its class, and providing melee users with utility that is not usually gained until later on.

The Axe serves as an example of the potential for unique per weapon charged attacks. This opens the door for more interesting game play with every melee weapon, but what should other weapons do when you  charge their attacks?

# The Point of this Thread
If you have any ideas for unique charged attacks (_or bashes_) for other melee weapons, post them here. Such changes could involve also changing the light attack of a weapon.

**Comment by Buggy123** [comment]
## charge attack ideas
### (most of which are sorta straight buffs and probably also stupid or wildly impractical)

 - Harpoon does a stabby stab instead of the weird swinging it does now, allowing it to pierce zombies  in a straight line to some degree. Or maybe, instead, it harpoons a zombie as if you threw it.

 - Sledgehammer (or hammers in general) gains the ability to headshot for extra damage. Think of it as you swinging the hammer overhead straight down onto the top of their skull. Ow.

 - Fist weapons could uppercut for extra damage and/or a *short* stun. Shame that they can't actually, yknow, charge attack.

 - The sanity sword goes from [dumb glaive](https://en.wikipedia.org/wiki/Glaive) to [cool glaive](http://static1.wikia.nocookie.net/__cb20130427134928/warframe/fr/images/a/a4/Warframe_The_Glaive.jpg) and is promptly thrown.

 - The t6 electric hammer , w/e it's called, does a [slam attack](https://i.dailymail.co.uk/i/pix/2013/04/23/article-0-1971F8D1000005DC-22_634x436.jpg)

 - Stabby-knife weapons [backstab](https://wiki.teamfortress.com/w/images/thumb/e/e0/Spybackstab.png/175px-Spybackstab.png) for extra damage (compared to a non-charged backstab) or instant kill (within reason), but does no damage at all if you don't hit the back.

That's all i can think of for now.

**Comment by ProfDru** [comment]
### Crowbar (T1)
**Charged Attack: _Teeth Strike_** 
- Follows the Mattock's head shot/leg damage considerations
- Counts as a sharp weapon for the purposes of sharpening stone

In this attack, the user attempts to dig the teeth of the crowbar downwards into their target, providing a greater reward for hitting vital areas, but doing much otherwise. The choice between slashing and bludgeoning would mostly be for flavor.

### Lead Pipe (T1) / Rebar Mace (T3)
**Charged Attack: _Concussive Strike_**
- In addition to viewpunch, the target recieves one second of tremor

Being given tremor suddenly can be very disorienting, which fits the role of the lead pipe and rebar mace perfectly.  Would make hitting those charged attacks much more appealing, although certain classes should be immune to this effect such as the Shadow Walker.
